{"address":"0x2f5B9748001556E69C9248f1649FA71332d7FF31","args":["0x8da3FDf1835a00A65FDA4B5900adf0442be6745D","0xaf95Ff5fB592646D86BF240B3CaE0903b6E4dd38","49911000000000000000000"],"code":"CALL_EXCEPTION","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000","errorArgs":["No such asset supplied or invalid balance"],"errorName":"Error","errorSignature":"Error(string)","level":"error","message":"call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)","method":"canWithdrawExtraCollateral(address,address,uint256)","reason":"No such asset supplied or invalid balance","service":"your-service-name","stack":"Error: call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-01T12:09:36.842Z","transaction":{"data":"0x30faeb7b0000000000000000000000008da3fdf1835a00a65fda4b5900adf0442be6745d000000000000000000000000af95ff5fb592646d86bf240b3cae0903b6e4dd38000000000000000000000000000000000000000000000a91ae446c30497c0000","to":"0x2f5B9748001556E69C9248f1649FA71332d7FF31"}}
{"address":"0x2f5B9748001556E69C9248f1649FA71332d7FF31","args":["0x8da3FDf1835a00A65FDA4B5900adf0442be6745D","0xaf95Ff5fB592646D86BF240B3CaE0903b6E4dd38","4991089000000000000000000"],"code":"CALL_EXCEPTION","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000","errorArgs":["No such asset supplied or invalid balance"],"errorName":"Error","errorSignature":"Error(string)","level":"error","message":"call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)","method":"canWithdrawExtraCollateral(address,address,uint256)","reason":"No such asset supplied or invalid balance","service":"your-service-name","stack":"Error: call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-02T06:21:33.582Z","transaction":{"data":"0x30faeb7b0000000000000000000000008da3fdf1835a00a65fda4b5900adf0442be6745d000000000000000000000000af95ff5fb592646d86bf240b3cae0903b6e4dd380000000000000000000000000000000000000000000420e77a12692483240000","to":"0x2f5B9748001556E69C9248f1649FA71332d7FF31"}}
{"address":"0x2f5B9748001556E69C9248f1649FA71332d7FF31","args":["0x8da3FDf1835a00A65FDA4B5900adf0442be6745D","0xaf95Ff5fB592646D86BF240B3CaE0903b6E4dd38","49911000000000000000000"],"code":"CALL_EXCEPTION","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000","errorArgs":["No such asset supplied or invalid balance"],"errorName":"Error","errorSignature":"Error(string)","level":"error","message":"call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)","method":"canWithdrawExtraCollateral(address,address,uint256)","reason":"No such asset supplied or invalid balance","service":"your-service-name","stack":"Error: call revert exception; VM Exception while processing transaction: reverted with reason string \"No such asset supplied or invalid balance\" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"canWithdrawExtraCollateral(address,address,uint256)\", data=\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294e6f207375636820617373657420737570706c696564206f7220696e76616c69642062616c616e63650000000000000000000000000000000000000000000000\", errorArgs=[\"No such asset supplied or invalid balance\"], errorName=\"Error\", errorSignature=\"Error(string)\", reason=\"No such asset supplied or invalid balance\", code=CALL_EXCEPTION, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Interface.decodeFunctionResult (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\interface.js:388:23)\n    at Contract.<anonymous> (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:329:56)\n    at step (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:48:23)\n    at Object.next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:29:53)\n    at fulfilled (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\contracts\\lib\\index.js:20:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-02T06:22:46.502Z","transaction":{"data":"0x30faeb7b0000000000000000000000008da3fdf1835a00a65fda4b5900adf0442be6745d000000000000000000000000af95ff5fb592646d86bf240b3cae0903b6e4dd38000000000000000000000000000000000000000000000a91ae446c30497c0000","to":"0x2f5B9748001556E69C9248f1649FA71332d7FF31"}}
{"argument":"amount","code":"INVALID_ARGUMENT","level":"error","message":"value out-of-bounds (argument=\"amount\", value=\"11579208923731620000000000000000000000000000000000000000000000000000000000000000\", code=INVALID_ARGUMENT, version=abi/5.7.0)","reason":"value out-of-bounds","service":"your-service-name","stack":"Error: value out-of-bounds (argument=\"amount\", value=\"11579208923731620000000000000000000000000000000000000000000000000000000000000000\", code=INVALID_ARGUMENT, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Logger.throwArgumentError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:250:21)\n    at Coder._throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\abstract-coder.js:41:16)\n    at NumberCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\number.js:46:18)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:74:19\n    at Array.forEach (<anonymous>)\n    at pack (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:60:12)\n    at TupleCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:71:33)\n    at AbiCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:91:15)","timestamp":"2023-05-02T09:47:27.795Z","value":"11579208923731620000000000000000000000000000000000000000000000000000000000000000"}
{"code":"NUMERIC_FAULT","fault":"overflow","level":"error","message":"overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"BigNumber.from\", value=1.157920892373162e+85, code=NUMERIC_FAULT, version=bignumber/5.7.0)","operation":"BigNumber.from","reason":"overflow","service":"your-service-name","stack":"Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"BigNumber.from\", value=1.157920892373162e+85, code=NUMERIC_FAULT, version=bignumber/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at throwFault (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:303:19)\n    at BigNumber.from (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:206:17)\n    at NumberCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\number.js:36:39)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:74:19\n    at Array.forEach (<anonymous>)\n    at pack (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:60:12)\n    at TupleCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:71:33)\n    at AbiCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:91:15)","timestamp":"2023-05-02T09:48:28.903Z","value":1.157920892373162e+85}
{"code":"NUMERIC_FAULT","fault":"overflow","level":"error","message":"overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"BigNumber.from\", value=1.157920892373162e+85, code=NUMERIC_FAULT, version=bignumber/5.7.0)","operation":"BigNumber.from","reason":"overflow","service":"your-service-name","stack":"Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault=\"overflow\", operation=\"BigNumber.from\", value=1.157920892373162e+85, code=NUMERIC_FAULT, version=bignumber/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at throwFault (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:303:19)\n    at BigNumber.from (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:206:17)\n    at NumberCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\number.js:36:39)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:74:19\n    at Array.forEach (<anonymous>)\n    at pack (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:60:12)\n    at TupleCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:71:33)\n    at AbiCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:91:15)","timestamp":"2023-05-02T09:48:50.867Z","value":1.157920892373162e+85}
{"argument":"amount","code":"INVALID_ARGUMENT","level":"error","message":"value out-of-bounds (argument=\"amount\", value=\"115792089237316200000000000000000000000000000000000000000000000000000000000000\", code=INVALID_ARGUMENT, version=abi/5.7.0)","reason":"value out-of-bounds","service":"your-service-name","stack":"Error: value out-of-bounds (argument=\"amount\", value=\"115792089237316200000000000000000000000000000000000000000000000000000000000000\", code=INVALID_ARGUMENT, version=abi/5.7.0)\n    at Logger.makeError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:238:21)\n    at Logger.throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:247:20)\n    at Logger.throwArgumentError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\logger\\lib\\index.js:250:21)\n    at Coder._throwError (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\abstract-coder.js:41:16)\n    at NumberCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\number.js:46:18)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:74:19\n    at Array.forEach (<anonymous>)\n    at pack (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:60:12)\n    at TupleCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:71:33)\n    at AbiCoder.encode (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:91:15)","timestamp":"2023-05-02T09:52:08.691Z","value":"115792089237316200000000000000000000000000000000000000000000000000000000000000"}
{"level":"error","message":"address is not defined","service":"your-service-name","stack":"ReferenceError: address is not defined\n    at balanceOf (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/controllers/balanceOfController.js:8:5)\n    at Layer.handle [as handle_request] (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2023-05-03T05:57:49.317Z"}
{"code":"ERR_HTTP_HEADERS_SENT","level":"error","message":"Cannot set headers after they are sent to the client","service":"your-service-name","stack":"Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (node:internal/errors:400:5)\n    at ServerResponse.setHeader (node:_http_outgoing:663:11)\n    at ServerResponse.header (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\response.js:794:10)\n    at ServerResponse.send (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\response.js:174:12)\n    at ServerResponse.json (C:\\Users\\EXPERT\\OneDrive\\Desktop\\L&B DApp\\backend\\node_modules\\express\\lib\\response.js:278:15)\n    at balanceOf (file:///C:/Users/EXPERT/OneDrive/Desktop/L&B%20DApp/backend/controllers/balanceOfController.js:18:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2023-05-03T05:59:22.828Z"}
